---
title: "Maria De Jesus R Notebook"
output:
  html_document:
    df_print: paged
    
---


## Hi Jonathon
I think this is what you wanted? I already finished this file but I wanted to insert this line to make sure this is what you meant.


<span style="color:red">Hey Maria, going forward, please keep your journal in a single .rmd document. I've cut and pasted from the two documents you created to demonstrate what we're looking for. The benefit of Github is that it allows you to continually make changes to a document and it will keep track of the iterative changes you're making, so we want you to learn and explore that functionality. Each week, download your RMD journal file from Github (which should contain comments from Ani or me) and simply add to it then upload the new version (keeping the same file name). The upload will create a new version of the file, but also hang on to the old version so you can look back at any point. Let me know if you have any questions! - Jonathon</span>


## Reflection on A.I.Discussion

After our discussion on A.I. in class, I found a lot more questions were brought up that were relevant to the article. I appreciated this article being written from a scientific (academic)  perspective, but I think this topic is part of a much broader conversation on how humans relate to the changing technological world. I think there were and are consequences to these changes that we need to prepare for. As scientist we have to recognize the discrepancies of access to many of these materials. Sure, in the scientific community we are already having this conversation in the United States but access is important to consider when we talk about the future. For countries that already lack direct access to publishing research articles and conducting research, the impacts of this technology could push their work back even further . Researchers in the global North are often already prioritized in terms of the funding they get for research and even the problems they get to solve because of these results. We already know science disproportionately benefits different people and is something that needs to be kept in mind when we begin creating legislation to control the use of artificial intelligence. 

<span style="color:red">I hadn't really thought about this. I've been viewing AI technology as a potential benefit to communities that have had trouble publishing previously (e.g., folks who don't use English as their first language), but you're right. Those who simply lack access to AI tools are just going to fall further behind. - Jonathon</span>

## Discussion on Equitable hiring practices 

For the class discussion on equitable hiring practices, I enjoyed discussing how to create a fully tangible plan for more equitable hiring practices. Both the students and the instructors brought up a lot of good points about how much work and effort implementing these ideas would be. Looking at the paper and tasks from a realist perspective is essential because there has to be a way to get everyone on board with these practices, especially those on the actual hiring committees. We know that not everyone is invested in the Diversity and Inclusion movement and having incentives for those that aren't is another problem that needs to be addressed. 

An aspect of this conversation that I find valuable is acknowledging the feelings involved in these initiatives. Both from academics from  minoritized groups and those in positions of power, or with identities that are already prioritized in the scientific community. I was listening to students with different backgrounds from myself and I really valued hearing their perspectives and talking about how the social systems in place in our countries are different and by default issues of diversity must be addressed differently. An enlightening idea to consider is that we must be flexible and adaptable when we move through the challenges of creating spaces where everyone feels welcome.

<span style="color:red">Yeah, I too was interested in hearing how the social systems in different countries are going to create novel challenges to increasing diversity in academia. Your voice was super helpful in class, particularly on this discussion. - Jonathon</span>


## Reproducibility crsis
Our discussion about reproducibility immediately reminded me of my experience in biology labs as an undergraduate student. I remember taking classes where a large part of the course objectives was learning how to conduct research and write a paper. I often found that many students would falsify their data just to be able to say something or form a conclusion, myself included. At no point was this ever addressed in that course which I found problematic. I think that trend continues on into the future career of many scientists because these maladaptive habits and thought patterns form early on in learning. Like I mentioned in class, I believe education is part of the issue of reproducibility as we have been taught to expect a certain outcome and if an experiment doesn't meet that outcome we often find shame or dissapointment in that. I think many students and those who later become scientists, were never taught how to fail with grace. Failure runs deeper than just a test. When our results are not what is expected or what our stakeholders want to see, there is a lot of pressure against scientist because they fear that they have failed. Whether it is a fear of failure, fear of losing funding or credibility, these anxieties are driving the reproducibility crisis. Overall, though I think that finances are the main driver of fudging results and not verifying our work, there is also a psychological factor at play.

<span style="color:red">There is some great literature on normalizing failure in scientific labs to ensure students are prepared for that. Failure is a HUGE part of being a scientist (paper rejections, not getting the funding, etc.), and when we're trained to think of failure as a sign of our own incompetence, it can certainly lead to problems. - Jonathon</span>


## Funding Research Discussion
I find that it was interesting for us to look at this funding issue from a pharmaceutical perspective because the structure and goals of how the funding works is a bit different. Goals matter right? Context matters. In the case of pharmaceuticals, we know there is bias towards making a drug that is being developed functional and safe because the goal of making money off of this. It is interesting because in science the goal is also to make money off their results but with a different function. Whereas in pharmacy there are larger impacts to humans if this data is falsified or, in biology there are different types of data and results that can be more theoretical and change the intentions of stakeholders.I didn't have a lot to say about this topic because I am still forming my opnions on it. 

<span style="color:red">No worries about not having much to say in class. Although I'm interested to hear you say "in science the goal is also to make money off their results..." I'm not sure I agree with that (certainly not why I'm in this business), but I see your point. Good pubs do probably lead to a better socioeconomic standing, so there is incentive to falsify data. - Jonathon</span>


## Citizen Science
The paper on citizen science was organized really well. I believe the writers thought of many asopects of limitations for citizen scicne. I think it would provide a good basis for scientists who are interested in starting a citizen science project The 6 stages provide a clear and actionable plan to utilize citizen science in an efficient way. With the design logistics, the aspect of communication is important but I wonder which modes of communication will really reach citizens. The public may find it less interesting if the interface is not attractive. I think something scientists don't take enough advantage of is calling in graphic designers and other artists into creating these apps. Even marketing specialists could present a benefit and perspective a scientist may not really think about. I see this as part of a bigger issue between scientists and "non-scientists", where science seems to be over-legitimized and doesn't consider how collaboration between fields and across professions would be beneficial by adding a more interdisciplinary approach. Another question I have is whether the data visualization is for scientists to do or can we call these people from other disciplines to work on this. In terms of reliability of these projects, I wonder what statistical analysis functions can be used to factor in public error. 

<span style="color:red">I struggle with this too. I tend to err on the side of "I'll just do everything myself because I know what I want it to look like" but I'm sure I could save myself a lot of time and headaches if I partnered with experts in many aspects of my work. - Jonathon</span>


## Working on Bins in Histogram
For today's class I learned a lot about how to use github, shiny and tinyverse to create more accessible data. Anya's output of the data they have created was so cool. It looks so advanced and clean and I plan to learn more about how to use these functional outputs. I am still very early on so these are important things for me to be introduced to. 

## Hypothesis Discussion
I think the creation of this literature review is very timely and useful. Funny enough, I am currently struggling to make space for a hypothesis on my NSF GRFP. I have also been teaching about the importance of hypothesis and how scientists make them, in the introductory biology lab that I teach. I personally believe hypothesis are somewhat dated in the context of interdisciplinary biology studies. Specifically because a hypothesis can look different based on what field you work in. It is hard to follow the same hypothesis model that has been used in one discipline and apply it to an unrelated field. I think that my generation is focusing more on impact driven,result based science rather than expanding on literature and this kind of work may not always have a hypothesis if the goal is to fix a problem. For example, it doesn't make sense to hypothesize that your model that is predicting child hunger will fail. Your goal is to succeed so this line of thinking is illogical. The paper also points point that the presence of a hypothesis does not generally determine if a grant application will be successful, which should tell us the format and usage of a hypothesis needs some improving. We also have to think about the context of when a hypothesis is necessary depending on if it is applied or theoretical. This may support the argument that hypothesis are necessary based on the context. Connecting the hypothesis to the broader application of your project is another aspect of this question, "Is a hypothesis necessary?" because in general that is what your hypothesis is meant to do. 
For Jonathons challenge: What is a set of objectives that can't be turned into a hypothesis?
I honestly don't know. Maybe you are correct and your argument wins.

## Predatory Journals
For our discussion on predatory journals there were a lot of contradicting opinions and implicit biases noted by everyone. I will first reference the article itself. I appreciated that they gave a direct definition for what counts as a "Predatory Journal". I think definitions are important because they provide distinct guidelines for what scientists should be looking for when determining if they would like to publish through a specific journal. I also liked that they had panelists from 10 different countries because this diverse set of perspectives also provides a broad spectrum of solutions for a problem that is now present at a global scale. I felt their diagram (with the bubbles) was well constructed and communicated the problem or disagreement between predatory journals lists and credible ones.

In terms of my own opinions on the topic, it seems the available resources noting predatory journals contradict each other and are not streamlined. Part of the solution to create a through and consistent list of predatory journals will be finding a point of collaboration between journals, scientific societies and other credible sources for verification. Even at an institutional level, the ethics board at Universities has the ability to create such a list for approved journals that the school will pay for a paper to be published. Additionally, this would require a process to apply for the inclusion for a new journal that may not be previously verified. I liked that the wildlife department has a list of journals to publish to, which I am sure makes it easier for their students to self-validate their choices for journal publication. The other question to consider is who is determining what a predatory journal is. One valid point that was brought up was that it may be easier to define and make a list of non-predatory journals than predatory ones. 

## Preregistration
The value of preregistration is apparent especially when pushing for the expansion of scientific knowledge rather than just publishing because its necessary. It's great that it forces the researcher to think about their project and the potential things that can go wrong before they go into it. It may even help people realize their project may not be as feasible and provide them the ability and time to create a contingency plan. It does seem like the pitfalls of preregistration may outweigh the benefits but it is on a case by case basis. There's no way to know every possible factor that could go wrong during a project and that may limit the ability for a researcher to submit a pre-registered project. A resolution does seem to be re-submitting updates to the project and continuing to receive that feedback from publishers. A benefit to preregistration could be production of more effective projects as the re-iteration process of scientific planning and thinking is emphasized.
The question I have though is if this pre-registration process is realistic to the timeline and limitations of scientific research.It seems almost all the researchers in the study had experience with preregistration and used it which may suggest it is realistic but I wonder how complex or limiting it could be for researchers doing novel work. I get nervous about intellectual property and the potential to have someone take your work and reproduce it and publish it faster. I also wonder how constraining it would be to have to get all of this work pre-registered to then not be able to complete the project and losing funds.

<span style="color:red">Yeah, I want to love this concept, but it certainly seems to fall apart in some ways when the rubber meets the road. - Jonathon</span>



## Blind Peer Reviews
I thought the article for our discussion was interesting, especially seeing how they conducted an applied study to look at status bias. I do think their question is important because this inherent bias of selecting to conduct peer review purely on the basis of a more established and known researcher makes the process of publication unfair to new writers and researchers. It doesn't surprise me that they found strong evidence suggesting the bias (more than it already is). It honestly makes sense based on human nature as well that the bias would be present.People like whats popular,there is a good amount of 'mob mentality' in every field whether its in science, art, or fashion. Realistically there is a popularity contest even in science. Different scientists names have weight in the research community.

<span style="color:red">Yeah, as a young(er) scientist, I often doubt myself when I disagree with those more established in the field. - Jonathon</span>


## Science Communication
For my presentation on science communication, I focused on the benefits of science communication skills for researchers and ways to leverage social media in the scientific space. Everyone provided great responses on the concerns and issues that come up with using social media as a conduit for communicating science. The main consequences that interested me were the danger of defamation and losing your credibility and being otherwise "cancelled" in your respective field. Something that I was not aware of was the potential danger of one scientist becoming the voice of a specific field from gaining popularity. That was an interesting perspective and I am not fully sure how such an issue would be addressed. The problem is ultimately controlled by the people consuming the information being presented to them. Unfortunately, misinformation is unavoidable in the digital age. The best we can do is inform viewers on being self-motivated consumers and using reason to determine if a source is reliable (This is the hard part).

<span style="color:red">Awesome work on this, Maria! - Jonathon</span>

## Mental Health in Academia 

I really enjoyed our discussion on mental health and elucidating some of the emotional issues students and P.I.'s can face. Mental health is important to consider for researchers and science as a whole. The bottom line is, everyone is going to experience hardship. That is not something we can change. What we can address is the level of compassion, support and respect we provide to our students and each other. Being kind is often overlooked as a strategy to support students. Like I mentioned in class, emphasizing a sort of mental check-in meeting once a semester or so may be beneficial for students and P.I.'s. This would take the pressure away from the student of having top bring it up to their P.I. that they may be struggling. It can potentially make it easier for P.I.'s as well so they don't come off as invasive. Especially towards students who prefer a distinct boundary between their work and personal life. Setting those boundaries up from the beginning creates a culture of trust between an advisor and their student.  Something I wanted to mention during class was the connection of capitalism to mental health. It is something I have been thinking about recently in general even outside of academia and in my life. At the end of the day, capitalism and how much we can produce controls our livelihood and how much joy we can experience. I personally know a lot of academics in my age range who attach much of their personal value and self-worth to how much they produce. And objectively that is how we measure success and how we are evaluated for our work. This was a great conversation to have near the end of the semester and during a very stressful time. Hopefully we were able to provide good feedback to you both on how we can become more supportive advisors.