---
title: "Maria De Jesus R Notebook"
output:
  html_document:
    df_print: paged
---

<span style="color:red">Hey Maria, going forward, please keep your journal in a single .rmd document. I've cut and pasted from the two documents you created to demonstrate what we're looking for. The benefit of Github is that it allows you to continually make changes to a document and it will keep track of the iterative changes you're making, so we want you to learn and explore that functionality. Each week, download your RMD journal file from Github (which should contain comments from Ani or me) and simply add to it then upload the new version (keeping the same file name). The upload will create a new version of the file, but also hang on to the old version so you can look back at any point. Let me know if you have any questions! - Jonathon</span>


## Reflection on A.I.Discussion

After our discussion on A.I. in class, I found a lot more questions were brought up that were relevant to the article. I appreciated this article being written from a scientific (academic)  perspective, but I think this topic is part of a much broader conversation on how humans relate to the changing technological world. I think there were and are consequences to these changes that we need to prepare for. As scientist we have to recognize the discrepancies of access to many of these materials. Sure, in the scientific community we are already having this conversation in the United States but access is important to consider when we talk about the future. For countries that already lack direct access to publishing research articles and conducting research, the impacts of this technology could push their work back even further . Researchers in the global North are often already prioritized in terms of the funding they get for research and even the problems they get to solve because of these results. We already know science disproportionately benefits different people and is something that needs to be kept in mind when we begin creating legislation to control the use of artificial intelligence. 

<span style="color:red">I hadn't really thought about this. I've been viewing AI technology as a potential benefit to communities that have had trouble publishing previously (e.g., folks who don't use English as their first language), but you're right. Those who simply lack access to AI tools are just going to fall further behind. - Jonathon</span>

## Discussion on Equitable hiring practices 

For the class discussion on equitable hiring practices, I enjoyed discussing how to create a fully tangible plan for more equitable hiring practices. Both the students and the instructors brought up a lot of good points about how much work and effort implementing these ideas would be. Looking at the paper and tasks from a realist perspective is essential because there has to be a way to get everyone on board with these practices, especially those on the actual hiring committees. We know that not everyone is invested in the Diversity and Inclusion movement and having incentives for those that aren't is another problem that needs to be addressed. 

An aspect of this conversation that I find valuable is acknowledging the feelings involved in these initiatives. Both from academics from  minoritized groups and those in positions of power, or with identities that are already prioritized in the scientific community. I was listening to students with different backgrounds from myself and I really valued hearing their perspectives and talking about how the social systems in place in our countries are different and by default issues of diversity must be addressed differently. An enlightening idea to consider is that we must be flexible and adaptable when we move through the challenges of creating spaces where everyone feels welcome.

<span style="color:red">Yeah, I too was interested in hearing how the social systems in different countries are going to create novel challenges to increasing diversity in academia. Your voice was super helpful in class, particularly on this discussion. - Jonathon</span>


## Reproducibility crsis
Our discussion about reproducibility immediately reminded me of my experience in biology labs as an undergraduate student. I remember taking classes where a large part of the course objectives was learning how to conduct research and write a paper. I often found that many students would falsify their data just to be able to say something or form a conclusion, myself included. At no point was this ever addressed in that course which I found problematic. I think that trend continues on into the future career of many scientists because these maladaptive habits and thought patterns form early on in learning. Like I mentioned in class, I believe education is part of the issue of reproducibility as we have been taught to expect a certain outcome and if an experiment doesn't meet that outcome we often find shame or dissapointment in that. I think many students and those who later become scientists, were never taught how to fail with grace. Failure runs deeper than just a test. When our results are not what is expected or what our stakeholders want to see, there is a lot of pressure against scientist because they fear that they have failed. Whether it is a fear of failure, fear of losing funding or credibility, these anxieties are driving the reproducibility crisis. Overall, though I think that finances are the main driver of fudging results and not verifying our work, there is also a psychological factor at play.

<span style="color:red">There is some great literature on normalizing failure in scientific labs to ensure students are prepared for that. Failure is a HUGE part of being a scientist (paper rejections, not getting the funding, etc.), and when we're trained to think of failure as a sign of our own incompetence, it can certainly lead to problems. - Jonathon</span>


## Funding Research Discussion
I find that it was interesting for us to look at this funding issue from a pharmaceutical perspective because the structure and goals of how the funding works is a bit different. Goals matter right? Context matters. In the case of pharmaceuticals, we know there is bias towards making a drug that is being developed functional and safe because the goal of making money off of this. It is interesting because in science the goal is also to make money off their results but with a different function. Whereas in pharmacy there are larger impacts to humans if this data is falsified or, in biology there are different types of data and results that can be more theoretical and change the intentions of stakeholders.I didn't have a lot to say about this topic because I am still forming my opnions on it. 

<span style="color:red">No worries about not having much to say in class. Although I'm interested to hear you say "in science the goal is also to make money off their results..." I'm not sure I agree with that (certainly not why I'm in this business), but I see your point. Good pubs do probably lead to a better socioeconomic standing, so there is incentive to falsify data. - Jonathon</span>


## Citizen Science
The paper on citizen science was organized really well. I believe the writers thought of many asopects of limitations for citizen scicne. I think it would provide a good basis for scientists who are interested in starting a citizen science project The 6 stages provide a clear and actionable plan to utilize citizen science in an efficient way. With the design logistics, the aspect of communication is important but I wonder which modes of communication will really reach citizens. The public may find it less interesting if the interfaceis not attractive. I think something scientists don't take enough advantage of is calling in grapphic designers and other artists into creating these apps. Even marketing specialists could present a benefit and perspective a scientist may not really think about. I see this as part of a bigger issue between scientists and "non-scientists", where science seems to be over-legitimized and doesn't consider how collaboration between fields and across professions would be beneficial by adding a more interdisciplinary approach. Another question I have is whether the data visualization is for scientists to do or can we call these people from other disciplines to work on this. In terms of reliability of these projects, I wonder what statistical analysis functions can be used to factor in public error. 

<span style="color:red">I struggle with this too. I tend to err on the side of "I'll just do everything myself because I know what I want it to look like" but I'm sure I could save myself a lot of time and headaches if I partnered with experts in many aspects of my work. - Jonathon</span>
